spring.application.name=auth-microservice

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/thesis_auth
spring.datasource.username= root
spring.datasource.password=${ROOTDB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_KEY}

#1h
jwt.expiration=86400000